
export class Authority {

    static READ_LOG = "READ_LOG";

    static ADD_PROFILE = "ADD_PROFILE";
    static EDIT_PROFILE = "EDIT_PROFILE";
    static DELETE_PROFILE = "DELETE_PROFILE";
    static READ_PROFILE = "READ_PROFILE";
    static CONFIGURE_PROFILE = "CONFIGURE_PROFILE";


    static ADD_FUNDING = "ADD_FUNDING";
    static DELETE_FUNDING = "DELETE_FUNDING";
    static EDIT_FUNDING = "EDIT_FUNDING";
    static READ_FUNDING = "READ_FUNDING";
    static IMPORT_FUNDING = "IMPORT_FUNDING";
    static EXPORT_FUNDING = "EXPORT_FUNDING";
    static DETAIL_FUNDING = "DETAIL_FUNDING";

    static ADD_CADRE_LOGIQUE = "ADD_CADRE_LOGIQUE";
    static EDIT_CADRE_LOGIQUE = "EDIT_CADRE_LOGIQUE";
    static DELETE_CADRE_LOGIQUE = "DELETE_CADRE_LOGIQUE";
    static READ_CADRE_LOGIQUE = "READ_CADRE_LOGIQUE";

    static ADD_MEETINGTYPE = "ADD_MEETINGTYPE";
    static EDIT_MEETINGTYPE = "EDIT_MEETINGTYPE";
    static DELETE_MEETINGTYPE = "DELETE_MEETINGTYPE";
    static READ_MEETINGTYPE = "READ_MEETINGTYPE";

    static READ_CATEGORY = "READ_CATEGORY";
    static ADD_CATEGORY = "ADD_CATEGORY";
    static EDIT_CATEGORY = "EDIT_CATEGORY";
    static DELETE_CATEGORY = "DELETE_CATEGORY";

    static READ_IMAGE = "READ_IMAGE";
    static ADD_IMAGE = "ADD_IMAGE";
    static EDIT_IMAGE = "EDIT_IMAGE";
    static DELETE_IMAGE = "DELETE_IMAGE";

    static READ_VIDEO = "READ_VIDEO";
    static ADD_VIDEO = "ADD_VIDEO";
    static EDIT_VIDEO = "EDIT_VIDEO";
    static DELETE_VIDEO = "DELETE_VIDEO";

    static READ_DOCUMENT = "READ_DOCUMENT";
    static ADD_DOCUMENT = "ADD_DOCUMENT";
    static EDIT_DOCUMENT = "EDIT_DOCUMENT";
    static DELETE_DOCUMENT = "DELETE_DOCUMENT";
    static READ_FILE_DOCUMENT = "READ_FILE_DOCUMENT";

    static READ_POINT_OF_VIGILANCE = "READ_POINT_OF_VIGILANCE";
    static ADD_POINT_OF_VIGILANCE = "ADD_POINT_OF_VIGILANCE";
    static EDIT_POINT_OF_VIGILANCE = "EDIT_POINT_OF_VIGILANCE";
    static DELETE_POINT_OF_VIGILANCE = "DELETE_POINT_OF_VIGILANCE";

    static ADD_STATUS = "ADD_STATUS";
    static DELETE_STATUS = "DELETE_STATUS";
    static EDIT_STATUS = "EDIT_STATUS";
    static READ_STATUS = "READ_STATUS";

    static ADD_FLAG = "ADD_FLAG";
    static DELETE_FLAG = "DELETE_FLAG";
    static EDIT_FLAG = "EDIT_FLAG";
    static READ_FLAG = "READ_FLAG";

    static READ_COUNTRY = "READ_COUNTRY";
    static ADD_COUNTRY = "ADD_COUNTRY";
    static EDIT_COUNTRY = "EDIT_COUNTRY";
    static DELETE_COUNTRY = "DELETE_COUNTRY";

    static ADD_CADRE_LOGIQUE_TYPE = "ADD_CADRE_LOGIQUE_TYPE";
    static EDIT_CADRE_LOGIQUE_TYPE = "EDIT_CADRE_LOGIQUE_TYPE";
    static DELETE_CADRE_LOGIQUE_TYPE = "DELETE_CADRE_LOGIQUE_TYPE";
    static READ_CADRE_LOGIQUE_TYPE = "READ_CADRE_LOGIQUE_TYPE";

    static READ_USER = "READ_USER";
    static ADD_USER = "ADD_USER";
    static EDIT_USER = "EDIT_USER";
    static DELETE_USER = "DELETE_USER";

    static ALL_ACCESS = "ALL_ACCESS";

    static READ_PHASE = "READ_PHASE";
    static ADD_PHASE = "ADD_PHASE";
    static EDIT_PHASE = "EDIT_PHASE";
    static DELETE_PHASE = "DELETE_PHASE";

    static READ_AGENT = " READ_AGENT";
    static ADD_AGENT = " ADD_AGENT";
    static EDIT_AGENT = "EDIT_AGENT";
    static DELETE_AGENT = "DELETE_AGENT";
    static IMPORT_AGENT = "IMPORT_AGENT";
    static EXPORT_AGENT = "EXPORT_AGENT";

    static ADD_STRUCTURE ="ADD_STRUCTURE";
    static EDIT_STRUCTURE ="EDIT_STRUCTURE";
    static DELETE_STRUCTURE ="DELETE_STRUCTURE";
    static READ_STRUCTURE ="READ_STRUCTURE";
    static IMPORT_STRUCTURE ="IMPORT_STRUCTURE";
    static EXPORT_STRUCTURE ="EXPORT_STRUCTURE"


    static READ_ACTIVITY_COMPONENT = "READ_ACTIVITY_COMPONENT";
    static ADD_ACTIVITY_COMPONENT = "ADD_ACTIVITY_COMPONENT";
    static EDIT_ACTIVITY_COMPONENT = "EDIT_ACTIVITY_COMPONENT";
    static DELETE_ACTIVITY_COMPONENT = "DELETE_ACTIVITY_COMPONENT";

    static READ_ALERTE = "READ_ALERTE";
    static ADD_ALERTE = "ADD_ALERTE";
    static EDIT_ALERTE = "EDIT_ALERTE";
    static DELETE_ALERTE = "DELETE_ALERTE";

    static READ_FINANCIAL_IMPACT = "READ_FINANCIAL_IMPACT";
    static ADD_FINANCIAL_IMPACT = "ADD_FINANCIAL_IMPACT";
    static EDIT_FINANCIAL_IMPACT = "EDIT_FINANCIAL_IMPACT";
    static DELETE_FINANCIAL_IMPACT = "DELETE_FINANCIAL_IMPACT";

    static READ_PROJECT = "READ_PROJECT";
    static ADD_PROJECT = "ADD_PROJECT";
    static EDIT_PROJECT = "EDIT_PROJECT";
    static DELETE_PROJECT = "DELETE_PROJECT";
    static IMPORT_PROJECT = "IMPORT_PROJECT";
    static EXPORT_PROJECT = "EXPORT_PROJECT";

    static READ_PROJECT_SETTINGS = "READ_PROJECT_SETTINGS";
    static READ_PROJECT_PROGRESS_TRACKING = "READ_PROJECT_PROGRESS_TRACKING";
    static READ_PROJECT_ACTIVITY_MONITORING = "READ_PROJECT_ACTIVITY_MONITORING";
    static READ_SUMMARY_SHEET = "READ_SUMMARY_SHEET";
    static READ_DETAIL = "READ_DETAIL";

    static READ_UGP = "READ_UGP";
    static ADD_UGP = "ADD_UGP";
    static EDIT_UGP = "EDIT_UGP";

    static DELETE_UGP = "DELETE_UGP";

    static READ_COMPONENT = "READ_COMPONENT";
    static ADD_COMPONENT = "ADD_COMPONENT";
    static EDIT_COMPONENT = "EDIT_COMPONENT";
    static DELETE_COMPONENT = "DELETE_COMPONENT";

    static READ_COMPONENT_REALIZATION = "READ_COMPONENT_REALIZATION";
    static ADD_COMPONENT_REALIZATION = "ADD_COMPONENT_REALIZATION";
    static EDIT_COMPONENT_REALIZATION = "EDIT_COMPONENT_REALIZATION";
    static DELETE_COMPONENT_REALIZATION = "DELETE_COMPONENT_REALIZATION";

    static READ_INTERVENTION_AREA = "READ_INTERVENTION_AREA";
    static ADD_INTERVENTION_AREA = "ADD_INTERVENTION_AREA";
    static EDIT_INTERVENTION_AREA = "EDIT_INTERVENTION_AREA";
    static DELETE_INTERVENTION_AREA = "DELETE_INTERVENTION_AREA";
    static EXPORT_INTERVENTION_AREA = "EXPORT_INTERVENTION_AREA"
    static IMPORT_INTERVENTION_AREA = "IMPORT_INTERVENTION_AREA"

    static READ_SUPERVISION_EXECUTION_STRUCTURE = "READ_ SUPERVISION_EXECUTION_STRUCTURE";
    static ADD_SUPERVISION_EXECUTION_STRUCTURE = "ADD_ SUPERVISION_EXECUTION_STRUCTURE";
    static EDIT_SUPERVISION_EXECUTION_STRUCTURE = "EDIT_ SUPERVISION_EXECUTION_STRUCTURE";
    static DELETE_SUPERVISION_EXECUTION_STRUCTURE = "DELETE_ SUPERVISION_EXECUTION_STRUCTURE";
    static EXPORT_SUPERVISION_EXECUTION_STRUCTURE = "EXPORT_SUPERVISION_EXECUTION_STRUCTURE"
    static IMPORT_SUPERVISION_EXECUTION_STRUCTURE = "IMPORT_SUPERVISION_EXECUTION_STRUCTURE"

    static READ_PARTNER = "READ_PARTNER";
    static ADD_PARTNER = "ADD_PARTNER";
    static EDIT_PARTNER = "EDIT_PARTNER";
    static DELETE_PARTNER = "DELETE_PARTNER";
    static EXPORT_PARTNER = "EXPORT_PARTNER";
    static IMPORT_PARTNER = "IMPORT_PARTNER";

    static READ_INDICATOR = "READ_INDICATOR";
    static ADD_INDICATOR = "ADD_INDICATOR";
    static EDIT_INDICATOR = "EDIT_INDICATOR";
    static DELETE_INDICATOR = "DELETE_INDICATOR";
    static EXPORT_INDICATOR = "EXPORT_INDICATOR";
    static IMPORT_INDICATOR = "IMPORT_INDICATOR";

    static READ_ACTOR = "READ_ACTOR";
    static ADD_ACTOR = "ADD_ACTOR";
    static EDIT_ACTOR = "EDIT_ACTOR";
    static DELETE_ACTOR = "DELETE_ACTOR";
    static EXPORT_ACTOR = "EXPORT_ACTOR";
    static IMPORT_ACTOR = "IMPORT_ACTOR";

    static READ_MILESTONE = "READ_MILESTONE";
    static ADD_MILESTONE = "ADD_MILESTONE";
    static EDIT_MILESTONE = "EDIT_MILESTONE";
    static DELETE_MILESTONE = "DELETE_MILESTONE";
    static IMPORT_MILESTONE = "IMPORT_MILESTONE";
    static EXPORT_MILESTONE = "EXPORT_MILESTONE";

    static READ_PROGRESS_TRACKING_COMPONENT = "READ_PROGRESS_TRACKING_COMPONENT";
    static ADD_PROGRESS_TRACKING_COMPONENT = "ADD_PROGRESS_TRACKING_COMPONENT";
    static EDIT_PROGRESS_TRACKING_COMPONENT = "EDIT_PROGRESS_TRACKING_COMPONENT";
    static DELETE_PROGRESS_TRACKING_COMPONENT = "DELETE_PROGRESS_TRACKING_COMPONENT";
    static IMPORT_PROGRESS_TRACKING_COMPONENT = "IMPORT_PROGRESS_TRACKING_COMPONENT";
    static EXPORT_PROGRESS_TRACKING_COMPONENT = "EXPORT_PROGRESS_TRACKING_COMPONENT";
    static READ_FILE_PROGRESS_TRACKING_COMPONENT = "READ_FILE_PROGRESS_TRACKING_COMPONENT";

    static READ_ISSUE_LOG_COMPONENT = "READ_ISSUE_LOG_COMPONENT";
    static ADD_ISSUE_LOG_COMPONENT = "ADD_ISSUE_LOG_COMPONENT";
    static EDIT_ISSUE_LOG_COMPONENT = "EDIT_ISSUE_LOG_COMPONENT";
    static DELETE_ISSUE_LOG_COMPONENT = "DELETE_ISSUE_LOG_COMPONENT";
    static EXPORT_ISSUE_LOG = "EXPORT_ISSUE_LOG";
    static IMPORT_ISSUE_LOG = "IMPORT_ISSUE_LOG";

    static READ_DISBURSEMENT_RATE = "READ_DISBURSEMENT_RATE";
    static ADD_DISBURSEMENT_RATE = "ADD_DISBURSEMENT_RATE";
    static EDIT_DISBURSEMENT_RATE = "EDIT_DISBURSEMENT_RATE";
    static DELETE_DISBURSEMENT_RATE = "DELETE_DISBURSEMENT_RATE";

    static READ_DELAY_IMPACT = "READ_DELAY_IMPACT";
    static ADD_DELAY_IMPACT = "ADD_DELAY_IMPACT";
    static EDIT_DELAY_IMPACT = "EDIT_DELAY_IMPACT";
    static DELETE_DELAY_IMPACT = "DELETE_DELAY_IMPACT";

    static READ_PROGRESS_TRACKING_INDICATOR = "READ_PROGRESS_TRACKING_INDICATOR";
    static ADD_PROGRESS_TRACKING_INDICATOR = "ADD_PROGRESS_TRACKING_INDICATOR";
    static EDIT_PROGRESS_TRACKING_INDICATOR = "EDIT_PROGRESS_TRACKING_INDICATOR";
    static DELETE_PROGRESS_TRACKING_INDICATOR = "DELETE_PROGRESS_TRACKING_INDICATOR";
    static IMPORT_PROGRESS_TRACKING_INDICATOR = "IMPORT_PROGRESS_TRACKING_INDICATOR";
    static EXPORT_PROGRESS_TRACKING_INDICATOR = "EXPORT_PROGRESS_TRACKING_INDICATOR";
    static READ_FILE_PROGRESS_TRACKING_INDICATOR = "READ_FILE_PROGRESS_TRACKING_INDICATOR";

    static READ_RISK = "READ_RISK";
    static ADD_RISK = "ADD_RISK";
    static EDIT_RISK = "EDIT_RISK";
    static DELETE_RISK = "DELETE_RISK";
    static IMPORT_RISK = "IMPORT_RISK";
    static EXPORT_RISK = "EXPORT_RISK";
    static PROBLEME_RISK = "PROBLEME_RISK";
    static RECOMMENDATION_RISK = "RECOMMENDATION_RISK";

    static READ_DATES_IMPORTANTES = "READ_DATES_IMPORTANTES";
    static ADD_DATES_IMPORTANTES = "ADD_DATES_IMPORTANTES";
    static EDIT_DATES_IMPORTANTES = "EDIT_DATES_IMPORTANTES";
    static DELETE_DATES_IMPORTANTES = "DELETE_DATES_IMPORTANTES";
    static EXPORT_DATES_IMPORTANTES = "EXPORT_DATES_IMPORTANTES";
    static IMPORT_DATES_IMPORTANTES = "IMPORT_DATES_IMPORTANTES";


    static READ_REF_INDICATOR = "READ_REF_INDICATOR";
    static ADD_REF_INDICATOR = "ADD_REF_INDICATOR";
    static EDIT_REF_INDICATOR = "EDIT_REF_INDICATOR";
    static DELETE_REF_INDICATOR = "DELETE_REF_INDICATOR";

    static READ_INDICATOR_TYPE = "READ_INDICATOR_TYPE";
    static ADD_INDICATOR_TYPE = "ADD_INDICATOR_TYPE";
    static EDIT_INDICATOR_TYPE = "EDIT_INDICATOR_TYPE";
    static DELETE_INDICATOR_TYPE = "DELETE_INDICATOR_TYPE";

    static READ_ASSIGNMENT_TYPE = "READ_ASSIGNMENT_TYPE";
    static ADD_ASSIGNMENT_TYPE = "ADD_ASSIGNMENT_TYPE";
    static EDIT_ASSIGNMENT_TYPE = "EDIT_ASSIGNMENT_TYPE";
    static DELETE_ASSIGNMENT_TYPE = "DELETE_ASSIGNMENT_TYPE";

    static READ_ROLE = "READ_ROLE";
    static ADD_ROLE = "ADD_ROLE";
    static EDIT_ROLE = "EDIT_ROLE";
    static DELETE_ROLE = "DELETE_ROLE";

    static READ_RESOLVE_CHANNEL = "READ_RESOLVE_CHANNEL";
    static ADD_RESOLVE_CHANNEL = "ADD_RESOLVE_CHANNEL";
    static EDIT_RESOLVE_CHANNEL = "EDIT_RESOLVE_CHANNEL";
    static DELETE_RESOLVE_CHANNEL = "DELETE_RESOLVE_CHANNEL";

    static READ_RESPONDENT = "READ_RESPONDENT";
    static ADD_RESPONDENT = "ADD_RESPONDENT";
    static EDIT_RESPONDENT = "EDIT_RESPONDENT";
    static DELETE_RESPONDENT = "DELETE_RESPONDENT";

    static READ_SOURCE = "READ_SOURCE";
    static ADD_SOURCE = "ADD_SOURCE";
    static EDIT_SOURCE = "EDIT_SOURCE";
    static DELETE_SOURCE = "DELETE_SOURCE";

    static READ_ISSUE_LOG = "READ_ISSUE_LOG";
    static ADD_ISSUE_LOG = "ADD_ISSUE_LOG";
    static EDIT_ISSUE_LOG = "EDIT_ISSUE_LOG";
    static DELETE_ISSUE_LOG = "DELETE_ISSUE_LOG";
    static ACTION_ISSUE_LOG = "ACTION_ISSUE_LOG";
    static RECOMMENDATION_ISSUE_LOG = "RECOMMENDATION_ISSUE_LOG";


    static READ_COMPLETED_ACTIVITY = "READ_COMPLETED_ACTIVITY";
    static ADD_COMPLETED_ACTIVITY = "ADD_COMPLETED_ACTIVITY";
    static EDIT_COMPLETED_ACTIVITY = "EDIT_COMPLETED_ACTIVITY";
    static DELETE_COMPLETED_ACTIVITY = "DELETE_COMPLETED_ACTIVITY";

    static READ_RECOMMENDATION = "READ_RECOMMENDATION";
    static ADD_RECOMMENDATION = "ADD_RECOMMENDATION";
    static EDIT_RECOMMENDATION = "EDIT_RECOMMENDATION";
    static DELETE_RECOMMENDATION = "DELETE_RECOMMENDATION";

    static READ_REVIEW ="READ_REVIEW";
    static ADD_REVIEW ="ADD_REVIEW";
    static EDIT_REVIEW ="EDIT_REVIEW";
    static DELETE_REVIEW ="DELETE_REVIEW";
    static EXPORT_REVIEW ="EXPORT_REVIEW";
    static IMPORT_REVIEW ="IMPORT_REVIEW";

    static READ_REVIEW_ISSUE_LOG ="READ_REVIEW_ISSUE_LOG";
    static ADD_REVIEW_ISSUE_LOG ="ADD_REVIEW_ISSUE_LOG";
    static EDIT_REVIEW_ISSUE_LOG ="EDIT_REVIEW_ISSUE_LOG";
    static DELETE_REVIEW_ISSUE_LOG ="DELETE_REVIEW_ISSUE_LOG";

    static READ_REVIEW_RISK = "READ_REVIEW_RISK";
    static ADD_REVIEW_RISK = "ADD_REVIEW_RISK";
    static EDIT_REVIEW_RISK = "EDIT_REVIEW_RISK";
    static DELETE_REVIEW_RISK = "DELETE_REVIEW_RISK";

    static READ_QUERY = "READ_QUERY";
    static ADD_QUERY = "ADD_QUERY";
    static EDIT_QUERY = "EDIT_QUERY";
    static DELETE_QUERY = "DELETE_QUERY";
    static EXPORT_QUERY = "DELETE_QUERY";
    static IMPORT_QUERY = "IMPORT_QUERY";

    static READ_QUERY_PROGESS = "READ_QUERY_PROGESS";
    static ADD_QUERY_PROGESS = "ADD_QUERY_PROGESS";
    static EDIT_QUERY_PROGESS = "EDIT_QUERY_PROGESS";
    static DELETE_QUERY_PROGESS = "DELETE_QUERY_PROGESS";


    static READ_STATE_PROGRESS = "READ_STATE_PROGRESS";
    static ADD_STATE_PROGRESS = "ADD_STATE_PROGRESS";
    static EDIT_STATE_PROGRESS = "EDIT_STATE_PROGRESS";
    static DELETE_STATE_PROGRESS = "DELETE_STATE_PROGRESS";

    static READ_MEDIATHEQUE = "READ_MEDIATHEQUE";
    static ADD_MEDIATHEQUE = "ADD_MEDIATHEQUE";
    static EDIT_MEDIATHEQUE = "EDIT_MEDIATHEQUE";
    static DELETE_MEDIATHEQUE = "DELETE_MEDIATHEQUE";

    static READ_FUNCTION = "READ_FUNCTION";
    static ADD_FUNCTION = "ADD_FUNCTION";
    static EDIT_FUNCTION = "EDIT_FUNCTION";
    static DELETE_FUNCTION = "DELETE_FUNCTION";

    static READ_REF_FLAG = "READ_REF_FLAG";
    static ADD_REF_FLAG = "ADD_REF_FLAG";
    static EDIT_REF_FLAG = "EDIT_REF_FLAG";
    static DELETE_REF_FLAG = "DELETE_REF_FLAG";

    static READ_FUNDING_TYPE = "READ_FUNDING_TYPE";
    static ADD_FUNDING_TYPE = "ADD_FUNDING_TYPE";
    static EDIT_FUNDING_TYPE = "EDIT_FUNDING_TYPE";
    static DELETE_FUNDING_TYPE = "DELETE_FUNDING_TYPE";

    static READ_CONDITIONALITY_TYPE = "READ_CONDITIONALITY_TYPE";
    static ADD_CONDITIONALITY_TYPE = "ADD_CONDITIONALITY_TYPE";
    static EDIT_CONDITIONALITY_TYPE = "EDIT_CONDITIONALITY_TYPE";
    static DELETE_CONDITIONALITY_TYPE = "DELETE_CONDITIONALITY_TYPE";

    static READ_NATURE = "READ_NATURE";
    static ADD_NATURE = "ADD_NATURE";
    static EDIT_NATURE = "EDIT_NATURE";
    static DELETE_NATURE = "DELETE_NATURE";

    static READ_SECTOR = "READ_SECTOR";
    static ADD_SECTOR = "ADD_SECTOR";
    static EDIT_SECTOR = "EDIT_SECTOR";
    static DELETE_SECTOR = "DELETE_SECTOR";
    static EXPORT_SECTOR = "EXPORT_SECTOR";
    static IMPORT_SECTOR = "IMPORT_SECTOR";

    static READ_SUB_SECTOR = "READ_SUB_SECTOR";
    static ADD_SUB_SECTOR = "ADD_SUB_SECTOR";
    static EDIT_SUB_SECTOR = "EDIT_SUB_SECTOR";
    static DELETE_SUB_SECTOR = "DELETE_SUB_SECTOR";

    static READ_REF_STATUS_TYPE = "READ_REF_STATUS_TYPE";
    static ADD_REF_STATUS_TYPE = "ADD_REF_STATUS_TYPE";
    static EDIT_REF_STATUS_TYPE = "EDIT_REF_STATUS_TYPE";
    static DELETE_REF_STATUS_TYPE = "DELETE_REF_STATUS_TYPE";

    static READ_TAG = " READ_TAG";
    static ADD_TAG = "ADD_TAG";
    static EDIT_TAG = "EDIT_TAG";
    static DELETE_TAG = "DELETE_TAG";

    static READ_PERIOD = " READ_PERIOD";
    static ADD_PERIOD = "ADD_PERIOD";
    static EDIT_PERIOD = "EDIT_PERIOD";
    static DELETE_PERIOD = "DELETE_PERIOD";

    static READ_PERIODICITY = "READ_PERIODICITY";
    static ADD_PERIODICITY = "ADD_PERIODICITY";
    static EDIT_PERIODICITY = "EDIT_PERIODICITY";
    static DELETE_PERIODICITY = "DELETE_PERIODICITY";

    static READ_PARTNER_GROUP = "READ_PARTNER_GROUP";
    static ADD_PARTNER_GROUP = "ADD_PARTNER_GROUP";
    static EDIT_PARTNER_GROUP = "EDIT_PARTNER_GROUP";
    static DELETE_PARTNER_GROUP = "DELETE_PARTNER_GROUP";

    static READ_SPECIFIC_NATURE = "READ_SPECIFIC_NATURE";
    static ADD_SPECIFIC_NATURE = "ADD_SPECIFIC_NATURE";
    static EDIT_SPECIFIC_NATURE = "EDIT_SPECIFIC_NATURE";
    static DELETE_SPECIFIC_NATURE = "DELETE_SPECIFIC_NATURE";

    static READ_REF_STATUS = "READ_REF_STATUS";
    static ADD_REF_STATUS = "ADD_REF_STATUS";
    static EDIT_REF_STATUS = "EDIT_SREF_STATUS";
    static DELETE_REF_STATUS = "DELETE_REF_STATUS";

    static READ_DOCUMENT_TYPE = "READ_DOCUMENT_TYPE";
    static ADD_DOCUMENT_TYPE = "ADD_DOCUMENT_TYPE";
    static EDIT_DOCUMENT_TYPE = "EDIT_DOCUMENT_TYPE";
    static DELETE_DOCUMENT_TYPE = "DELETE_DOCUMENT_TYPE";

    static READ_SUB_CATEGORY = " READ_SUB_CATEGORY";
    static ADD_SUB_CATEGORY = "ADD_SUB_CATEGORY";
    static EDIT_SUB_CATEGORY = "EDIT_SUB_CATEGORY";
    static DELETE_SUB_CATEGORY = "DELETE_SUB_CATEGORY";

    static READ_UNIT = "READ_UNIT";
    static ADD_UNIT = "ADD_UNIT";
    static EDIT_UNIT = "EDIT_UNIT";
    static DELETE_UNIT = "DELETE_UNIT";

    static READ_AXE_PSE = "READ_AXE_PSE";
    static ADD_AXE_PSE = "ADD_AXE_PSE";
    static EDIT_AXE_PSE = "EDIT_AXE_PSE";
    static DELETE_AXE_PSE = "DELETE_AXE_PSE";

    static READ_CRITICITY = "READ_CRITICITY";
    static ADD_CRITICITY = "ADD_CRITICITY";
    static EDIT_CRITICITY = "EDIT_CRITICITY";
    static DELETE_CRITICITY = "DELETE_CRITICITY";

    static READ_PREPARATION = "READ_PREPARATION";
    static ADD_PREPARATION = "ADD_PREPARATION";
    static EDIT_PREPARATION = "EDIT_PREPARATION";
    static DELETE_PREPARATION = "DELETE_PREPARATION";
    static EXPORT_PREPARATION = "EXPORT_PREPARATION";
    static IMPORT_PREPARATION = "IMPORT_PREPARATION";

    static READ_CONDITIONALITY = "READ_CONDITIONALITY";
    static ADD_CONDITIONALITY = "ADD_CONDITIONALITY";
    static EDIT_CONDITIONALITY = "EDIT_CONDITIONALITY";
    static DELETE_CONDITIONALITY = "DELETE_CONDITIONALITY";
    static EXPORT_CONDITIONALITY = "EXPORT_CONDITIONALITY";
    static IMPORT_CONDITIONALITY = "IMPORT_CONDITIONALITY";

    static READ_ASSIGNMENT = "READ_ASSIGNMENT";
    static ADD_ASSIGNMENT = "ADD_ASSIGNMENT";
    static EDIT_ASSIGNMENT = "EDIT_ASSIGNMENT";
    static DELETE_ASSIGNMENT = "DELETE_ASSIGNMENT";
    static EXPORT_ASSIGNMENT = "EXPORT_ASSIGNMENT";
    static IMPORT_ASSIGNMENT = "IMPORT_ASSIGNMENT";

    static READ_ASSIGNMENT_ISSUE_LOG = "READ_ASSIGNMENT_ISSUE_LOG";
    static READ_ASSIGNMENT_RECOMMENDATION = "READ_ASSIGNMENT_ISSUE_LOG";
    static ADD_ASSIGNMENT_ISSUE_LOG = "ADD_ASSIGNMENT_ISSUE_LOG";
    static EDIT_ASSIGNMENT_ISSUE_LOG = "EDIT_ASSIGNMENT_ISSUE_LOG";
    static DELETE_ASSIGNMENT_ISSUE_LOG = "DELETE_ASSIGNMENT_ISSUE_LOG";

    static READ_MEETING = "READ_MEETING";
    static ADD_MEETING = "ADD_MEETING";
    static EDIT_MEETING = "EDIT_MEETING";
    static DELETE_MEETING = "DELETE_MEETING";

    static READ_DASHBOARD = "READ_DASHBOARD";
    static ADD_DASHBOARD = "ADD_DASHBOARD";
    static EDIT_DASHBOARD = "EDIT_DASHBOARD";
    static DELETE_DASHBOARD = "DELETE_DASHBOARD";

    static DASHBOARD = [Authority.ALL_ACCESS,
    Authority.READ_DASHBOARD, Authority.ADD_DASHBOARD, Authority.EDIT_DASHBOARD, Authority.DELETE_DASHBOARD
    ]
    static SECURITY = [Authority.ALL_ACCESS,
    Authority.READ_USER, Authority.ADD_USER, Authority.EDIT_USER, Authority.DELETE_USER,
    Authority.READ_PROFILE, Authority.ADD_PROFILE, Authority.EDIT_PROFILE, Authority.DELETE_PROFILE, Authority.CONFIGURE_PROFILE
    ]
    static REFERENTIEL = [Authority.ALL_ACCESS,
    Authority.READ_PHASE, Authority.ADD_PHASE, Authority.EDIT_PHASE, Authority.DELETE_PHASE,
    Authority.READ_AGENT, Authority.ADD_AGENT, Authority.EDIT_AGENT, Authority.DELETE_AGENT,
    Authority.READ_AXE_PSE, Authority.ADD_AXE_PSE, Authority.EDIT_AXE_PSE, Authority.DELETE_AXE_PSE,
    Authority.READ_CADRE_LOGIQUE, Authority.ADD_CADRE_LOGIQUE, Authority.EDIT_CADRE_LOGIQUE, Authority.DELETE_CADRE_LOGIQUE,
    Authority.READ_CADRE_LOGIQUE_TYPE, Authority.ADD_CADRE_LOGIQUE_TYPE, Authority.EDIT_CADRE_LOGIQUE_TYPE, Authority.DELETE_CADRE_LOGIQUE_TYPE,
    Authority.READ_CATEGORY, Authority.ADD_CATEGORY, Authority.EDIT_CATEGORY, Authority.DELETE_CATEGORY,
    Authority.READ_COUNTRY, Authority.ADD_COUNTRY, Authority.EDIT_COUNTRY, Authority.DELETE_COUNTRY,
    Authority.READ_SUB_CATEGORY, Authority.ADD_SUB_CATEGORY, Authority.EDIT_SUB_CATEGORY, Authority.DELETE_SUB_CATEGORY,
    Authority.READ_PERIODICITY, Authority.ADD_PERIODICITY, Authority.EDIT_PERIODICITY, Authority.DELETE_PERIODICITY,
    Authority.READ_PARTNER_GROUP, Authority.ADD_PARTNER_GROUP, Authority.EDIT_PARTNER_GROUP, Authority.DELETE_PARTNER_GROUP,
    Authority.READ_TAG, Authority.ADD_TAG, Authority.EDIT_TAG, Authority.DELETE_TAG,
    Authority.READ_PERIOD, Authority.ADD_PERIOD, Authority.EDIT_PERIOD, Authority.DELETE_PERIOD,
    Authority.READ_STATE_PROGRESS, Authority.ADD_STATE_PROGRESS, Authority.EDIT_STATE_PROGRESS, Authority.DELETE_STATE_PROGRESS,
    Authority.READ_UNIT, Authority.ADD_UNIT, Authority.EDIT_UNIT, Authority.DELETE_UNIT,
    Authority.READ_SECTOR, Authority.ADD_SECTOR, Authority.EDIT_SECTOR, Authority.DELETE_SECTOR,
    Authority.READ_SUB_SECTOR, Authority.ADD_SUB_SECTOR, Authority.EDIT_SUB_SECTOR, Authority.DELETE_SUB_SECTOR,
    Authority.READ_DELAY_IMPACT, Authority.ADD_DELAY_IMPACT, Authority.EDIT_DELAY_IMPACT, Authority.DELETE_DELAY_IMPACT,
    Authority.READ_FINANCIAL_IMPACT, Authority.ADD_FINANCIAL_IMPACT, Authority.EDIT_FINANCIAL_IMPACT, Authority.DELETE_FINANCIAL_IMPACT,
    Authority.READ_REF_STATUS_TYPE, Authority.ADD_REF_STATUS_TYPE, Authority.EDIT_REF_STATUS_TYPE, Authority.DELETE_REF_STATUS_TYPE,
    Authority.READ_REF_STATUS, Authority.ADD_REF_STATUS, Authority.EDIT_REF_STATUS, Authority.DELETE_REF_STATUS,
    Authority.READ_REF_INDICATOR, Authority.ADD_REF_INDICATOR, Authority.EDIT_REF_INDICATOR, Authority.DELETE_REF_INDICATOR,
    Authority.READ_INDICATOR_TYPE, Authority.ADD_INDICATOR_TYPE, Authority.EDIT_INDICATOR_TYPE, Authority.DELETE_INDICATOR_TYPE,
    Authority.READ_ASSIGNMENT_TYPE, Authority.ADD_ASSIGNMENT_TYPE, Authority.EDIT_ASSIGNMENT_TYPE, Authority.DELETE_ASSIGNMENT_TYPE,
    Authority.READ_ROLE, Authority.ADD_ROLE, Authority.EDIT_ROLE, Authority.DELETE_ROLE,
    Authority.READ_RESOLVE_CHANNEL, Authority.ADD_RESOLVE_CHANNEL, Authority.EDIT_RESOLVE_CHANNEL, Authority.DELETE_RESOLVE_CHANNEL,
    Authority.READ_RESPONDENT, Authority.ADD_RESPONDENT, Authority.EDIT_RESPONDENT, Authority.DELETE_RESPONDENT,
    Authority.READ_SOURCE, Authority.ADD_SOURCE, Authority.EDIT_SOURCE, Authority.DELETE_SOURCE,
    Authority.READ_STRUCTURE, Authority.ADD_STRUCTURE, Authority.EDIT_STRUCTURE, Authority.DELETE_STRUCTURE, Authority.IMPORT_STRUCTURE, Authority.EXPORT_STRUCTURE,
    Authority.READ_MEDIATHEQUE, Authority.ADD_MEDIATHEQUE, Authority.EDIT_MEDIATHEQUE, Authority.DELETE_MEDIATHEQUE,
    Authority.READ_FUNCTION, Authority.ADD_FUNCTION, Authority.EDIT_FUNCTION, Authority.DELETE_FUNCTION,
    Authority.READ_REF_FLAG, Authority.ADD_REF_FLAG, Authority.EDIT_REF_FLAG, Authority.DELETE_REF_FLAG,
    Authority.READ_FUNDING_TYPE, Authority.ADD_FUNDING_TYPE, Authority.EDIT_FUNDING_TYPE, Authority.DELETE_FUNDING_TYPE,
    Authority.READ_CONDITIONALITY_TYPE, Authority.ADD_CONDITIONALITY_TYPE, Authority.EDIT_CONDITIONALITY_TYPE, Authority.DELETE_CONDITIONALITY_TYPE,
    Authority.READ_NATURE, Authority.ADD_NATURE, Authority.EDIT_NATURE, Authority.DELETE_NATURE,
    Authority.READ_SPECIFIC_NATURE, Authority.ADD_SPECIFIC_NATURE, Authority.EDIT_SPECIFIC_NATURE, Authority.DELETE_SPECIFIC_NATURE,
    Authority.READ_DOCUMENT_TYPE, Authority.ADD_DOCUMENT_TYPE, Authority.EDIT_DOCUMENT_TYPE, Authority.DELETE_DOCUMENT_TYPE,
    Authority.READ_CRITICITY, Authority.ADD_CRITICITY, Authority.EDIT_CRITICITY, Authority.DELETE_CRITICITY,
    Authority.READ_MEETINGTYPE, Authority.ADD_MEETINGTYPE, Authority.EDIT_MEETINGTYPE, Authority.DELETE_MEETINGTYPE

    ]

    static ALERTE = [Authority.ALL_ACCESS,
    Authority.READ_ALERTE, Authority.ADD_ALERTE, Authority.EDIT_ALERTE, Authority.DELETE_ALERTE
    ]
    static MANAGEMENT_PROJECT = [Authority.ALL_ACCESS,
    Authority.READ_PROJECT, Authority.ADD_PROJECT, Authority.EDIT_PROJECT, Authority.DELETE_PROJECT,
    Authority.EXPORT_PROJECT, Authority.IMPORT_PROJECT,
    Authority.READ_PROJECT_SETTINGS, Authority.READ_PROJECT_PROGRESS_TRACKING,
    Authority.READ_PROJECT_ACTIVITY_MONITORING,
    Authority.READ_SUMMARY_SHEET, Authority.READ_DETAIL
    ]

    static MODULE = {
        DASHBOARD: {
            DASHBOARD: [Authority.ALL_ACCESS, Authority.READ_DASHBOARD, Authority.ADD_DASHBOARD, Authority.EDIT_DASHBOARD, Authority.DELETE_DASHBOARD],
        },
        MANAGEMENT_PROJECT: {
            PROJECT_LIST: [Authority.ALL_ACCESS,
            Authority.READ_PROJECT, Authority.ADD_PROJECT, Authority.EDIT_PROJECT, Authority.DELETE_PROJECT,
            Authority.EXPORT_PROJECT, Authority.IMPORT_PROJECT,
            Authority.READ_PROJECT_SETTINGS, Authority.READ_PROJECT_PROGRESS_TRACKING,
            Authority.READ_PROJECT_ACTIVITY_MONITORING,
            Authority.READ_SUMMARY_SHEET, Authority.READ_DETAIL],
        },
        REFERENTIEL: {
            PHASE: [Authority.READ_PHASE, Authority.ADD_PHASE, Authority.EDIT_PHASE, Authority.DELETE_PHASE, Authority.ALL_ACCESS],
            AGENT: [Authority.READ_AGENT, Authority.ADD_AGENT, Authority.EDIT_AGENT, Authority.DELETE_AGENT, Authority.ALL_ACCESS],
            AXE_PSE: [Authority.READ_AXE_PSE, Authority.ADD_AXE_PSE, Authority.EDIT_AXE_PSE, Authority.DELETE_AXE_PSE, Authority.ALL_ACCESS],
            CADRE_LOGIQUE: [Authority.READ_CADRE_LOGIQUE, Authority.ADD_CADRE_LOGIQUE, Authority.EDIT_CADRE_LOGIQUE, Authority.DELETE_CADRE_LOGIQUE, Authority.ALL_ACCESS],
            CADRE_LOGIQUE_TYPE: [Authority.READ_CADRE_LOGIQUE_TYPE, Authority.ADD_CADRE_LOGIQUE_TYPE, Authority.EDIT_CADRE_LOGIQUE_TYPE, Authority.DELETE_CADRE_LOGIQUE_TYPE, Authority.ALL_ACCESS],
            CATEGORY: [Authority.READ_CATEGORY, Authority.ADD_CATEGORY, Authority.EDIT_CATEGORY, Authority.DELETE_CATEGORY, Authority.ALL_ACCESS],
            COUNTRY: [Authority.READ_COUNTRY, Authority.ADD_COUNTRY, Authority.EDIT_COUNTRY, Authority.DELETE_COUNTRY, Authority.ALL_ACCESS],
            SUB_CATEGORY: [Authority.READ_SUB_CATEGORY, Authority.ADD_SUB_CATEGORY, Authority.EDIT_SUB_CATEGORY, Authority.DELETE_SUB_CATEGORY, Authority.ALL_ACCESS],
            PERIODICITY: [Authority.READ_PERIODICITY, Authority.ADD_PERIODICITY, Authority.EDIT_PERIODICITY, Authority.DELETE_PERIODICITY, Authority.ALL_ACCESS],
            PARTNER_GROUP: [Authority.READ_PARTNER_GROUP, Authority.ADD_PARTNER_GROUP, Authority.EDIT_PARTNER_GROUP, Authority.DELETE_PARTNER_GROUP, Authority.ALL_ACCESS],
            TAG: [Authority.READ_TAG, Authority.ADD_TAG, Authority.EDIT_TAG, Authority.DELETE_TAG, Authority.ALL_ACCESS],
            PERIOD: [Authority.READ_PERIOD, Authority.ADD_PERIOD, Authority.EDIT_PERIOD, Authority.DELETE_PERIOD, Authority.ALL_ACCESS],
            STATE_PROGRESS: [Authority.READ_STATE_PROGRESS, Authority.ADD_STATE_PROGRESS, Authority.EDIT_STATE_PROGRESS, Authority.DELETE_STATE_PROGRESS, Authority.ALL_ACCESS],
            UNIT: [Authority.READ_UNIT, Authority.ADD_UNIT, Authority.EDIT_UNIT, Authority.DELETE_UNIT, Authority.ALL_ACCESS],
            SECTOR: [Authority.READ_SECTOR, Authority.ADD_SECTOR, Authority.EDIT_SECTOR, Authority.DELETE_SECTOR, Authority.ALL_ACCESS],
            SUB_SECTOR: [Authority.READ_SUB_SECTOR, Authority.ADD_SUB_SECTOR, Authority.EDIT_SUB_SECTOR, Authority.DELETE_SUB_SECTOR, Authority.ALL_ACCESS],
            DELAY_IMPACT: [Authority.READ_DELAY_IMPACT, Authority.ADD_DELAY_IMPACT, Authority.EDIT_DELAY_IMPACT, Authority.DELETE_DELAY_IMPACT, Authority.ALL_ACCESS],
            FINANCIAL_IMPACT: [Authority.READ_FINANCIAL_IMPACT, Authority.ADD_FINANCIAL_IMPACT, Authority.EDIT_FINANCIAL_IMPACT, Authority.DELETE_FINANCIAL_IMPACT, Authority.ALL_ACCESS],
            REF_STATUS_TYPE: [Authority.READ_REF_STATUS_TYPE, Authority.ADD_REF_STATUS_TYPE, Authority.EDIT_REF_STATUS_TYPE, Authority.DELETE_REF_STATUS_TYPE, Authority.ALL_ACCESS],
            REF_STATUS: [Authority.READ_REF_STATUS, Authority.ADD_REF_STATUS, Authority.EDIT_REF_STATUS, Authority.DELETE_REF_STATUS, Authority.ALL_ACCESS],
            REF_INDICATOR: [Authority.READ_REF_INDICATOR, Authority.ADD_REF_INDICATOR, Authority.EDIT_REF_INDICATOR, Authority.DELETE_REF_INDICATOR, Authority.ALL_ACCESS],
            INDICATOR_TYPE: [Authority.READ_INDICATOR_TYPE, Authority.ADD_INDICATOR_TYPE, Authority.EDIT_INDICATOR_TYPE, Authority.DELETE_INDICATOR_TYPE, Authority.ALL_ACCESS],
            ASSIGNMENT_TYPE: [Authority.READ_ASSIGNMENT_TYPE, Authority.ADD_ASSIGNMENT_TYPE, Authority.EDIT_ASSIGNMENT_TYPE, Authority.DELETE_ASSIGNMENT_TYPE, Authority.ALL_ACCESS],
            ROLE: [Authority.READ_ROLE, Authority.ADD_ROLE, Authority.EDIT_ROLE, Authority.DELETE_ROLE, Authority.ALL_ACCESS],
            RESOLVE_CHANNEL: [Authority.READ_RESOLVE_CHANNEL, Authority.ADD_RESOLVE_CHANNEL, Authority.EDIT_RESOLVE_CHANNEL, Authority.DELETE_RESOLVE_CHANNEL, Authority.ALL_ACCESS],
            RESPONDENT: [Authority.READ_RESPONDENT, Authority.ADD_RESPONDENT, Authority.EDIT_RESPONDENT, Authority.DELETE_RESPONDENT, Authority.ALL_ACCESS],
            SOURCE: [Authority.READ_SOURCE, Authority.ADD_SOURCE, Authority.EDIT_SOURCE, Authority.DELETE_SOURCE, Authority.ALL_ACCESS],
            STRUCTURE: [Authority.READ_STRUCTURE, Authority.ADD_STRUCTURE, Authority.EDIT_STRUCTURE, Authority.DELETE_STRUCTURE, Authority.IMPORT_STRUCTURE, Authority.EXPORT_STRUCTURE, Authority.ALL_ACCESS],
            MEDIATHEQUE: [Authority.READ_MEDIATHEQUE, Authority.ADD_MEDIATHEQUE, Authority.EDIT_MEDIATHEQUE, Authority.DELETE_MEDIATHEQUE, Authority.ALL_ACCESS],
            FUNCTION: [Authority.READ_FUNCTION, Authority.ADD_FUNCTION, Authority.EDIT_FUNCTION, Authority.DELETE_FUNCTION, Authority.ALL_ACCESS],
            REF_FLAG: [Authority.READ_REF_FLAG, Authority.ADD_REF_FLAG, Authority.EDIT_REF_FLAG, Authority.DELETE_REF_FLAG, Authority.ALL_ACCESS],
            FUNDING_TYPE: [Authority.READ_FUNDING_TYPE, Authority.ADD_FUNDING_TYPE, Authority.EDIT_FUNDING_TYPE, Authority.DELETE_FUNDING_TYPE, Authority.ALL_ACCESS],
            CONDITIONALITY_TYPE: [Authority.READ_CONDITIONALITY_TYPE, Authority.ADD_CONDITIONALITY_TYPE, Authority.EDIT_CONDITIONALITY_TYPE, Authority.DELETE_CONDITIONALITY_TYPE, Authority.ALL_ACCESS],
            NATURE: [Authority.READ_NATURE, Authority.ADD_NATURE, Authority.EDIT_NATURE, Authority.DELETE_NATURE, Authority.ALL_ACCESS],
            SPECIFIC_NATURE: [Authority.READ_SPECIFIC_NATURE, Authority.ADD_SPECIFIC_NATURE, Authority.EDIT_SPECIFIC_NATURE, Authority.DELETE_SPECIFIC_NATURE, Authority.ALL_ACCESS],
            DOCUMENT_TYPE: [Authority.READ_DOCUMENT_TYPE, Authority.ADD_DOCUMENT_TYPE, Authority.EDIT_DOCUMENT_TYPE, Authority.DELETE_DOCUMENT_TYPE, Authority.ALL_ACCESS],
            CRITICITY: [Authority.READ_CRITICITY, Authority.ADD_CRITICITY, Authority.EDIT_CRITICITY, Authority.DELETE_CRITICITY, Authority.ALL_ACCESS],
            MEETINGTYPE: [Authority.READ_MEETINGTYPE, Authority.ADD_MEETINGTYPE, Authority.EDIT_MEETINGTYPE, Authority.DELETE_MEETINGTYPE, Authority.ALL_ACCESS]
        },
        SECURITY: {
            USER: [Authority.ALL_ACCESS, Authority.READ_USER, Authority.ADD_USER, Authority.EDIT_USER, Authority.DELETE_USER],
            PROFILE: [Authority.ALL_ACCESS, Authority.READ_PROFILE, Authority.ADD_PROFILE, Authority.EDIT_PROFILE, Authority.DELETE_PROFILE, Authority.CONFIGURE_PROFILE],
            LOG: [Authority.ALL_ACCESS, Authority.READ_LOG],
        },
        ALERTE: {
            ALERTE: [Authority.ALL_ACCESS, Authority.READ_ALERTE, Authority.ADD_ALERTE, Authority.EDIT_ALERTE, Authority.DELETE_ALERTE]
        }
    };


}

